version: '3'
services:
    app:
        build:
            context: .
            dockerfile: docker
        image: digitalocean.com/php
        container_name: app-paracord
        restart: unless-stopped
        tty: true
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    webserver:
        image: nginx:alpine
        container_name: webserver-paracord
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./docker/nginx/nginx.conf/:/etc/nginx/conf.d/nginx.conf
        depends_on:
            - app

    redis:
        image: redis:latest
        container_name: redis-paracord
        command: redis-server --requirepass ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
